import React, { useContext } from 'react';
import Head from 'next/head';
import useIssue from '@/hooks/useIssue';
import { UserContext } from '@/provider/userProvider';
import Navbar from '@/components/Navbar';
import IssueCard from '@/components/Card/issueCard';

export default function Mainpage() {
  const { issueList } = useIssue();
  const userData = useContext(UserContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {/* gonna remove this when production finished IssueCard style */}
      <main className="h-[1000px] flex justify-center mt-10">

        <ul className="h-auto overflow-y-auto">
          {issueList.map((issue) => (
            <li key={issue.issueId} className="mt-10 first:mt-0">
              <IssueCard issue={issue} />
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
