import React from 'react';
import Head from 'next/head';
import useUser from '@/hooks/useUser';

export default function Mainpage() {
  const { user } = useUser();
  console.log(user);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Hello welcome to main page
      </main>
    </>
  );
}
