import React, { useState } from 'react';
import Head from 'next/head';
import useIssue from '@/hooks/useIssue';
import Navbar from '@/components/Navbar';
import IssueCard from '@/components/Card/issueCard';
import Button from '@/components/Button';
import { useRouter } from 'next/router';
import TagGroup from '@/components/Tag/TagGroup';
import { Tag } from '@/types/issue';

export default function Mainpage() {
  const router = useRouter();
  const { issueList } = useIssue();
  const [selectedTag, setSelectedTag] = useState<Tag>('Open');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex flex-row justify-center w-full mt-4 overflow-y-hidden">

        <div className="flex flex-col w-[50vw]">

          <div>
            <Button classNames="w-fit h-10 bg-slate-200" onClick={() => router.push('/task/newTask')}>
              add new Issue
            </Button>
          </div>

          <div className="flex flex-row justify-between">
            <TagGroup selectedTag={selectedTag} setSelectedTag={setSelectedTag} />
            <div>
              <span>Search</span>
            </div>
          </div>

          <ul className="flex flex-col items-center w-full h-auto overflow-y-auto">
            {issueList.map((issue) => (
              <li key={issue.issueId} className="mt-10 first:mt-0 w-[80%]">
                <IssueCard issue={issue} />
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}
